name: Daily ETL and Data Commit

on:
  schedule:
    # Runs every day at 22:00 UTC (equivalent to 5:00 PM EST, 6:00 PM EDT)
    - cron: "0 22 * * *"
  workflow_dispatch: {}

permissions:
  contents: write  # allow pushing updates back to the repo

concurrency:
  group: etl-daily
  cancel-in-progress: false

jobs:
  run-etl:
    name: Run ETL and commit data
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run ETL script
        env:
          PYTHONUNBUFFERED: '1'
        run: |
          python etl-market-data.py

      - name: Commit and push changes (data folder only)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          # Stage only data folder
          git add data/
          # Check if there are changes in data/
          if [ -n "$(git status --porcelain data/)" ]; then
            git commit -m "Daily ETL: update data ($(date -u +'%Y-%m-%d %H:%M:%S') UTC)"
            git push
          else
            echo "No changes to commit in data/"
          fi
